# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registeredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('course', models.TextField()),
                ('enrollmentno', models.TextField()),
                ('year', models.IntegerField()),
                ('detailforappointment', models.TextField(default='')),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
