# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-02 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0002_auto_20180401_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='course',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='enrollmentno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
