# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-15 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0003_auto_20180402_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='timestamp',
        ),
    ]
