# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-15 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0004_remove_appuser_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='detailforappointment',
            field=models.CharField(max_length=200),
        ),
    ]
