# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0006_auto_20180418_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='regdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
