# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0007_appuser_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='regdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
