# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0008_auto_20180420_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='timeslot_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='timeslot_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
